let arr = [ "Adrauna",
  "Agya",
  "Agya",
  "Ahirauli",
  "Ahirauli",
  "Ahirauli",
  "Ahirauli",
  "Ahirauli Kusumhi",
  "Amadaria",
  "Amawa Bazar",
  "Amdiha",
  "Anantpur",
  "Arak Pur",
  "Arazi Sankhapar",
  "Ashana",
  "Atharaha",
  "Awarahi Kritpura",
  "Awarawa",
  "Aziz Nagar",
  "Ba;Gaha Khurd",
  "Badahara",
  "Badahara",
  "Badaraha",
  "Badaraha Naga",
  "Baghnath",
  "Bahuas",
  "Bairia",
  "Bairia",
  "Balua",
  "Baluwa",
  "Baluwa Rampur Sri Pal",
  "Banchara",
  "Bankata",
  "Baraipur",
  "Barauli",
  "Barawa",
  "Barawa Kala",
  "Barawa Khurd",
  "Bardiha",
  "Bardiha",
  "Barhya Buzurg",
  "Barhya Khurd",
  "Barsaina",
  "Bartha",
  "Barwa",
  "Barwa",
  "Barwa Asthan",
  "Barwa Chhatardas",
  "Barwa Khas",
  "Barwa Kotwa",
  "Barwa Mahadewa",
  "Basahiya Urf Kaptan Ganj",
  "Basantpur",
  "Basantpur",
  "Basdila",
  "Batrauli",
  "Baulia",
  "Belbhadra Chhapra",
  "Belwa",
  "Belwa",
  "Belwa",
  "Belwa Buzurg",
  "Belwa Khurd",
  "Belwa Sudama",
  "Belwa Urf Bairiya",
  "Belwa Urf Belwania",
  "Bhagwanpur",
  "Bhagwanpur Buzurg",
  "Bhagwanpur Khurd",
  "Bhainsahi",
  "Bhaluha",
  "Bhaluhi",
  "Bhaluhi",
  "Bharpurwa Urf Muzaffarpur",
  "Bharsar Khas",
  "Bharsar Narain",
  "Bharwalia",
  "Bhat Gawan",
  "Bhatgaon",
  "Bhathahi Buzurg",
  "Bhathahi Khurd",
  "Bhiswa",
  "Bhiswa",
  "Bhiswa Math Walgir",
  "Bhiswa Urf Bishanpur",
  "Bhiswabel Bhariya",
  "Bhiura",
  "Bihuli Nisfi",
  "Bihuli Shumali Urf Hanuman Gan",
  "Bijai Kaf",
  "Binduar",
  "Bishunipura",
  "Bishunpur Kaithwaliya",
  "Bishunpur Urf Thuthi",
  "Bishunpura",
  "Bishunpura",
  "Bishunpura",
  "Bishunpura",
  "Bishunpura",
  "Bodarwar",
  "Brindaban",
  "Chak Abdul Islam",
  "Chak Narain",
  "Chak Nilkanth",
  "Chandarpur",
  "Chatur Chak",
  "Chhapiya",
  "Chhapra Bhagat",
  "Chhitauni",
  "Chilua",
  "Chiurapali",
  "Dadupar",
  "Deo Kali",
  "Deokali Urf Chakiya",
  "Deorajpur",
  "Deoria",
  "Deoria Babu",
  "Deotaha",
  "Deulia Maniya Chhapra",
  "Deurwa",
  "Deurwa",
  "Dhanaha",
  "Dhanauji Khas",
  "Dhanauji Mafi",
  "Dharah Khurd",
  "Dharampur",
  "Dharha Buzurg",
  "Dharm Samda",
  "Dharmauli",
  "Dharmauli",
  "Dharmauli",
  "Dhaura",
  "Dhodharahi",
  "Dhuan Tikar",
  "Dom Barwa",
  "Dubauli",
  "Dubauli",
  "Dumari",
  "Dumari Arjun",
  "Dumari Maldwan",
  "Dumari Sawangi Patti",
  "Dumdumawa Urf Majhila",
  "Farad Mundera",
  "Farna",
  "Gajara",
  "Gamhirpur",
  "Ganeshpur",
  "Gangrai",
  "Gaunar",
  "Gaunariya",
  "Ghiwahi",
  "Ghoda Deur",
  "Ghogharaha",
  "Ghortap",
  "Ghurahupur",
  "Gidaha Dhanna",
  "Gidha Chak Bairiya",
  "Gonha",
  "Gopalpur",
  "Gopalpur Biraicha",
  "Gotha Pokhar Bhinda",
  "Hanskhor",
  "Harpur Barwa",
  "Harpur Machhagar",
  "Harpur Sukhar",
  "Hasan Ganj",
  "Hata (NP)",
  "Hata Khas",
  "Holia",
  "Indarpur",
  "Inder Senwa",
  "Jagdishpur",
  "Jagdishpur",
  "Jamali",
  "Jamuan",
  "Jamun Barwa",
  "Jamuni Barwa",
  "Jhanga",
  "Jhanjhanpur",
  "Jolahpur",
  "Kaptanganj (NP)",
  "Karamaha",
  "Karitin",
  "Karmaha Ugersen",
  "Karmahi",
  "Khabharabhar",
  "Khairatawa",
  "Khairatawa",
  "Khajhawa",
  "Khokhia Mubarakpur",
  "Khotaha",
  "Khotahi",
  "Khurhuriya",
  "Kodara",
  "Kohrauli",
  "Kotawa",
  "Kotwa",
  "Kuinchwar",
  "Kundur",
  "Kusumahi",
  "Kusumha",
  "Kusumha",
  "Lachhimipur",
  "Lachhmipur",
  "Lakhima",
  "Lala Chhapra",
  "Lalipar",
  "Langari",
  "Langari",
  "Laxmipur",
  "Laxmipur",
  "Lehani",
  "Lehni",
  "Lohipar",
  "Lohjhar",
  "Madaraha",
  "Madhwalia",
  "Magdiha",
  "Mahadanpur Sihuliya",
  "Mahadeo Chapra",
  "Mahmada Zameen Sikatiya",
  "Mahuari",
  "Mahuawa",
  "Mahuawa",
  "Mahuawa Khurd",
  "Mahuawa Masjidia",
  "Mahui",
  "Mahui",
  "Mahui",
  "Mahulaiya",
  "Mahuwa Bujurg",
  "Malukahi",
  "Mandey Rai",
  "Mangalpur",
  "Mangalpur Urf Mangrua",
  "Mansoor Ganj",
  "Math Surajgir",
  "Mathauli",
  "Mathia Barghat",
  "Mathiya",
  "Mathiya",
  "Mathiya Urf Akataha",
  "Mehda",
  "Mir Patti",
  "Mishra Dharah",
  "Mishrauli",
  "Mohan Munddra",
  "Mohanpur",
  "Morwan",
  "Morwan Urf Gopala",
  "Moti Chak",
  "Moti Pakar",
  "Moti Pakar",
  "Moti Pakar Kabilasaha",
  "Moti Pakar Shri Kant",
  "Mudila",
  "Mujahana",
  "Mujahana Haitim",
  "Mujahana Rahim",
  "Mujdiha",
  "Munadih",
  "Mundera",
  "Mundera",
  "Mundera",
  "Mundera",
  "Mundera Lala",
  "Nanhu Mundera",
  "Narainpur",
  "Narainpur",
  "Narainpur",
  "Naumunda",
  "Nawapar",
  "Nayapur",
  "Pachar",
  "Padari",
  "Padari",
  "Padauli",
  "Padkhori",
  "Pagar",
  "Pagara",
  "Pagara",
  "Pagara",
  "Paikauli",
  "Paikauli",
  "Paikauli",
  "Pakadi Madaraha",
  "Pakari",
  "Pakari",
  "Pakari",
  "Pakari Bangar",
  "Pakari Bantir Saunha",
  "Pakari Bantir Urf Mehndiganj",
  "Pakri",
  "Papaur",
  "Paroraha",
  "Parsa",
  "Parsauni",
  "Parsauni",
  "Parsiya",
  "Partawal",
  "Patan",
  "Patana Mishrauli",
  "Patani",
  "Patani",
  "Pathar Dewa",
  "Patkhauli",
  "Pemali",
  "Phardaha",
  "Phulwaria Magarib",
  "Phulwaria Masriq",
  "Pidra",
  "Pindari",
  "Pipariya",
  "Pipra",
  "Pipra",
  "Pipra",
  "Pipra Humel",
  "Pipra Kapur",
  "Pipra Lalmani",
  "Pipra Mafi",
  "Pipra Shital Urf Bakarabad",
  "Pipra Urf Titala",
  "Piprahi Bhadkulwa",
  "Pipraicha",
  "Pokhar Bhinda",
  "Pokhar Bhinda",
  "Pokhar Bhinda",
  "Puran Chhapra",
  "Radhiya Deoria",
  "Raghunathpur",
  "Rajmandir",
  "Rajpur",
  "Ramkola",
  "Ramkola (NP)",
  "Rampur",
  "Rampur",
  "Rampur",
  "Rampur Bagaha",
  "Rampur Buzurg",
  "Rampur Mafi",
  "Rampur Maharath",
  "Rampur Misri",
  "Rampur Patwa",
  "Rampur Sohrauna",
  "Rani Kaf",
  "Ranipar Urf Hariya",
  "Rohua Machhariya Gaon",
  "Rohuwasat Bharia",
  "Sahbazpur",
  "Sahjauli",
  "Sakarauli",
  "Sakhauli",
  "Sakhopar",
  "Saneramal Chhapra",
  "Sankhapar Mafi",
  "Sapaha",
  "Sat Bhariya",
  "Semara",
  "Semari Maheshpur",
  "Senduar",
  "Shahpur",
  "Shekhpurwa",
  "Shivpor Mathiya",
  "Sidhawat",
  "Sihulia Mathia",
  "Sihuliya",
  "Sikta",
  "Siktiya",
  "Sinduria Bishunpur",
  "Singhana",
  "Singhari",
  "Singhpur",
  "Singhpur",
  "Sirsia",
  "Sirsia",
  "Sirsiya",
  "Siswa",
  "Situhiya",
  "Sodhara",
  "Sohani",
  "Sohrauna",
  "Sohrauna",
  "Somali",
  "Sona Paker Urf Thakurbari",
  "Sonbarsa",
  "Sonbarsa",
  "Sonia",
  "Subidhiya Khurd",
  "Subudhiya Buzurg",
  "Sudhiyani",
  "Sugga Pakar",
  "Sukrauli",
  "Sukrauli",
  "Sumahatar",
  "Sumha Khor",
  "Tarkulwa",
  "Tawakalpur",
  "Telgaona",
  "Tharua Dih",
  "Tikar",
  "Tikari",
  "Turk Diha",
  "Turkaha",
  "Urdaha",
  "Waghra Deur"
]
