let arr = [ "Abhnayakpur",
  "Ahirauli Raja",
  "Ahirauli Ram",
  "Amawa",
  "Amawa Buzurg",
  "Amawa Dubey",
  "Ambarpur",
  "Amwa Sri Bubey",
  "Andhya",
  "Anrudhwa",
  "Araji Kachhuhiya",
  "Arazi Bairagi Patti",
  "Arazi Balak Patti",
  "Arazi Kotwa",
  "Arazi Parsauni",
  "Arazi Sidhawe",
  "Arusawa",
  "Asmanpur",
  "Asogawa Buzurg",
  "Asogawa Khurd",
  "Avarwa Safiganj",
  "Badaraha Lachhmipur",
  "Badwrav",
  "Bahorapur",
  "Baidauli Mahua Dih",
  "Baij Nathpur",
  "Bairagi Patti",
  "Bairia Raja",
  "Bakanaha",
  "Bakulahar Kalan",
  "Bakulahar Khurd",
  "Balak Patti",
  "Baliawa",
  "Bankata Bazar",
  "Bantail",
  "Baradaha Bazar",
  "Barahara",
  "Barwa Bazar",
  "Barwa Jangar",
  "Barwa Sukhdav",
  "Basdeopur",
  "Basdila",
  "Basdila Durjan",
  "Batar Dera",
  "Batesara",
  "Batlohia",
  "Beili",
  "Belwa Alamdas",
  "Belwa Buzurg",
  "Belwa Durga Rai",
  "Belwa Kalan",
  "Belwa Khurd",
  "Belwa Khurd",
  "Belwa Palakdhari Singh",
  "Belwa Ramjas",
  "Belwachhit Urf Kajipur",
  "Bhagwanpur",
  "Bhainsaha",
  "Bhaisahi",
  "Bhaluha Khas",
  "Bhaluhi Madari Patti",
  "Bharauli",
  "Bharsarwa",
  "Bharwalia",
  "Bhathahi Babu",
  "Bhathahi Buzurg",
  "Bhathahi Daria Tola",
  "Bhathahi Khurd",
  "Bhathahi Raja",
  "Bhathawa",
  "Bhatwalia",
  "Bhatwalia",
  "Bisambhapur",
  "Bishun Pura",
  "Bishunpur Magurahi",
  "Bishunpur Raja",
  "Bishunpur Shekh Fazalali",
  "Chainpur",
  "Chak Daiya",
  "Chakar Patti",
  "Chakia",
  "Changauna Jamubi",
  "Chara Gaha",
  "Chaura Digar",
  "Chaura Khas",
  "Chaura Ramtawakalshahi",
  "Chaura Sri Krishan Sahai",
  "Chaurahi Urf Anjahi",
  "Cheagauna Shumali",
  "Chhahun",
  "Chhatthu Katya",
  "Chirgoda",
  "Chiutaha",
  "Dahari Patti",
  "Damwatia",
  "Darajiya",
  "Dehwa Patti",
  "Devi Chak",
  "Dhanaha",
  "Dhanauji",
  "Dhanauji Kalon",
  "Dhanauji Khurd",
  "Dhanha Urf Maludih",
  "Dharni Chhapar",
  "Dhaurahara",
  "Dhokraha",
  "Dhundhwalia",
  "Dhuria",
  "Dighawa Buzurg",
  "Diguwa Khurd",
  "Dul Dulia",
  "Dumar Churamani Chhapra",
  "Dumari",
  "Dumari",
  "Dumari",
  "Durgwalia",
  "Ekderwa Auwal",
  "Ekderwa Doyam",
  "Farendaha",
  "Fazi Nagar (CT)",
  "Fursatpur",
  "Garahiya",
  "Gaura Khor",
  "Gobarahi",
  "Gopal Garh",
  "Gurwalia",
  "Haraiya",
  "Hata",
  "Hilgarh",
  "Jamunia Mahuawa",
  "Jauramanrakhan",
  "Jhankaul",
  "Jhugwa",
  "Jigana",
  "Jigani",
  "Jokwa Buzurg",
  "Jokwa Khurd",
  "Judawaniya",
  "Kachhuhiya Janubi",
  "Kachuhiya Shumali",
  "Kanaura",
  "Kankhoria",
  "Karjahi",
  "Karmaini Premwalia",
  "Kasturba",
  "Kathgharhi",
  "Katya Mainuddin",
  "Khadda",
  "Khairatia",
  "Khardar Goga Patti",
  "Khardewa",
  "Khartari",
  "Khedani",
  "Khesari Gidha",
  "Khorabar",
  "Kohra",
  "Koilaswa Bazar",
  "Kolhua",
  "Kotwa",
  "Kripa Patti",
  "Kuchaya",
  "Kundwa Urf Dilipnagar",
  "Kurahawa",
  "Kurmauta",
  "Kurmauta",
  "Kurmauta",
  "Kushinagar (NP)",
  "Lathaur",
  "Lav Kush Pashchim Patti",
  "Laxmipur",
  "Laxmipur Misra",
  "Loharwalia",
  "Madanpur",
  "Madaraha",
  "Madhopur",
  "Madhopur",
  "Madhuria",
  "Mahason",
  "Mahua Dih Laungrapur",
  "Mahuawa",
  "Mahuawa",
  "Mahuawa Buzurg",
  "Mahui Buzurg",
  "Mahui Khurd",
  "Mainpur",
  "Mangalpur",
  "Manpur",
  "Matahiniya",
  "Mathauli",
  "Mathia Besambhar Madhopur",
  "Mathia Naraipur",
  "Mathia Tapsi",
  "Misrauli",
  "Momin Tekulia",
  "Mundera",
  "Mundera Ratan Patti",
  "Mundera Urf Mugalhi",
  "Nadwa Bisunpur",
  "Naika Chhapra",
  "Nakahni",
  "Nakataha Urf Harihar Chhapar",
  "Narainpur",
  "Narainpur",
  "Narkatia",
  "Narkatia Buzurg",
  "Narkatia Khurd",
  "Narsar",
  "Natha Patti",
  "Natwalia",
  "Naugaon",
  "Naugawan",
  "Nibi",
  "Nonia Patti",
  "Ojhawalia",
  "Pacharukhia",
  "Pakari",
  "Pakari Urf Pakariyar",
  "Paras Khand",
  "Parashu Rampur",
  "Parewatar",
  "Parsahwa",
  "Parsauna",
  "Parsauna Buzurg",
  "Parsauna Khurd",
  "Parsauna Urf Bir Chhapra",
  "Parsauni",
  "Parsauni",
  "Parsauni Khurd",
  "Parsauni Mukundaha",
  "Parwarpar",
  "Patai",
  "Pataya",
  "Pathkhauli",
  "Patkhauli",
  "Phagupur Bishunpur",
  "Pipra",
  "Pipra Jham",
  "Pipra Rajab",
  "Pipra Tiwari",
  "Pipri",
  "Pokhar Bhinda",
  "Pokhar Bhinda",
  "Prem Walia",
  "Puraini",
  "Purandarpur",
  "Rahasu Sumali Patti",
  "Rahasujanubi Patti",
  "Rajwa Bar",
  "Ram Nagar",
  "Rambar Buzurg",
  "Ramhwalia",
  "Rampur Patti",
  "Rampur Urf Khushihal Tola",
  "Rawatpar",
  "Rudawalia",
  "Sabia",
  "Sakhopar",
  "Sampur Hatwa",
  "Sapha",
  "Sariya Mahanth Patti",
  "Sathiaon",
  "Sekhwania Khurd",
  "Semara",
  "Semara Urf Jhungwa",
  "Semari",
  "Semra Dhusi",
  "Shahpur",
  "Shampur",
  "Shanker Patti",
  "Shekhwania Buzurg",
  "Sherpur Badahara",
  "Shivpur Buzurg",
  "Shivpur Dih",
  "Shripata Khand",
  "Siarha",
  "Sidhawe",
  "Sikaria Urf Ram Nagar",
  "Singaha",
  "Sirsia Khoiya",
  "Sisia",
  "Siswa",
  "Sohang",
  "Sohsa Mathiya",
  "Sohsa Patti Gausi",
  "Sonbarsa",
  "Sondia",
  "Sukarauli",
  "Sukhpurwa",
  "Sumahi Buzurg",
  "Sumahi Khurd",
  "Taruanwa",
  "Tekuatar",
  "Tekulia Urf Dubauli",
  "Tenua",
  "Tetaria",
  "Turk Walia Dariyao Singh",
  "Turkwalia"
]
