let arr = [ "Adhar Chhapra",
  "Ahirauli",
  "Ahirauli",
  "Ahirauli Buzurg",
  "Ahirauli Khurd",
  "Anant Chhapra",
  "Andhari Bari",
  "Arjun Chhapra",
  "Atardiha",
  "Babhnauli",
  "Babhnauli",
  "Babuia Harpur",
  "Badal Chhapra",
  "Badal Chhapra",
  "Badal Chhapra",
  "Badhara",
  "Badrauna",
  "Badwa Chhapra",
  "Baghparna",
  "Baglaha",
  "Bahadurganj",
  "Bahelia",
  "Bahera",
  "Bahor Chhapra",
  "Bahor Chhapra Abadkari",
  "Bahora Chhapra",
  "Bairagi Patti",
  "Bakuladah",
  "Bal Chand Chhapra",
  "Bal Govind Chhapra",
  "Baldeo Chhapra",
  "Baldiha",
  "Bali",
  "Balkudia",
  "Balochaha",
  "Baluahi",
  "Bandhu Chhapra",
  "Bandhu Chhapra",
  "Bandhu Chhapra",
  "Bandhwa",
  "Bandi Chhapra",
  "Banjari Patti",
  "Barahaj",
  "Barahra",
  "Barawapurdil",
  "Bargaha",
  "Bargaon",
  "Barhwalia Buzurg",
  "Barhwalia Khurd",
  "Barwa",
  "Barwa Kalan",
  "Barwa Khurd",
  "Barwa Khurd",
  "Barwa Ratanpur",
  "Basantpur",
  "Basantpur",
  "Basantpur",
  "Basauli",
  "Basdila",
  "Basdila",
  "Basdila Jungal",
  "Bashia Banbirpur",
  "Batisaha",
  "Batrauli",
  "Belahi",
  "Belwa",
  "Belwa Baburam",
  "Belwa Jungal",
  "Belwa Misir",
  "Betia",
  "Bhagwanpur",
  "Bhaisaha Mus.+ Aht.",
  "Bhajan Chhapra",
  "Bharwalia",
  "Bhatwalia",
  "Bheri Jungal",
  "Bherihari No.1",
  "Bherihari No.2",
  "Bhimal Chhapra",
  "Bhiswa Lala",
  "Bhiswa Sarkari",
  "Bhitha Abad Kari",
  "Bhojauli Buzurg",
  "Bhojauli Khurd",
  "Bhui Sohara",
  "Bhujauli",
  "Bijai Chhapra",
  "Bindwalia",
  "Biraith",
  "Birbal Chhapra",
  "Bisheshwarpur",
  "Bishunpura",
  "Bishunpura Buzurg",
  "Bishunpura Khurd",
  "Bishunpura Khurd",
  "Bodhi Chhapra",
  "Bulahwa",
  "Burhawa Jungal",
  "Chain Patti",
  "Chaiti Musahari",
  "Chak Chintaman",
  "Chakdhar Chhapra",
  "Chakhani Bhoj Chhapra",
  "Chakhni Bhmi Hari Patti",
  "Chakhni Mafi",
  "Chakhnipuran Chhapra",
  "Chakia",
  "Chamar Diha",
  "Chandarpur",
  "Chatur Chhapra",
  "Chauparia",
  "Chaura Khas",
  "Chauria",
  "Chhitan Patti",
  "Chhitaoni Jungal",
  "Chhitauni",
  "Chirgora Khas",
  "Chitaha",
  "Dal Chhapra",
  "Dambatia",
  "Dandopur",
  "Dangarha",
  "Dankutwa",
  "Darbahaganga Chhapra",
  "Dargauli",
  "Deo Gaon",
  "Deoria",
  "Deoria Pandey",
  "Deotaha",
  "Devipur Mus.+ Aht.",
  "Dhamauli",
  "Dhan Garha",
  "Dhanauji Abadkari",
  "Dhanha",
  "Dharampur",
  "Dharampur Buzurg",
  "Dharampur Khurd",
  "Dharmauli Urf Zinda Chhapra",
  "Dharni Patti",
  "Dhaurahara Abadkari",
  "Dheer Patti",
  "Dhinuhua",
  "Dhir Chhapra",
  "Dholah Ramnagar Mus. Dholah",
  "Dholha",
  "Dhorahi",
  "Dhuri Chhapra",
  "Dibni",
  "Doman Chhapra",
  "Domara Khurd",
  "Dubauli",
  "Dudhahi Ghat",
  "Dukhran Patti",
  "Dumar Bhar",
  "Dumara Buzurg",
  "Dumari",
  "Ekdanga Bhajan Chhapra",
  "Ekdangi",
  "Ekwanhi Khurd",
  "Ekwanhi Urf Bhagwatpur",
  "Fakira Chhapra",
  "Feru Chhapra",
  "Gaithihaw Mus. Ghithihaw Aht.",
  "Gambharia Khurd",
  "Gambhiria Buzurg",
  "Ganbhir Chhapra",
  "Ganeshi Patti",
  "Gangauli",
  "Gangrani",
  "Garhia Basantpur",
  "Garib Chhapra",
  "Ghorghatia",
  "Ghur Chhapra",
  "Gohti Buzurg",
  "Gohti Khurd",
  "Gonhi Jungal",
  "Gopalpur",
  "Gulelha",
  "Gulriha",
  "Hajari Patti",
  "Hanumanganj Mus.+ Aht.",
  "Har Keshwa",
  "Haraiya Buzurg",
  "Haraiya Khurd",
  "Hariharpur",
  "Harju Chhapra",
  "Harka Baijnath Mal",
  "Harka Ghurmal",
  "Harka Hanmantgir",
  "Harka Malik Patti",
  "Harpur",
  "Harpur Maphi",
  "Harpur Tappa Batesara 46",
  "Harpur Tappa Naugaon 55",
  "Hasna",
  "Hathia",
  "Hirnaha",
  "Hirnaha",
  "Horilapur",
  "Indra Senwa",
  "Jai Chhapra",
  "Jai Chhapra",
  "Jai Singh Chhapra",
  "Jakhinia",
  "Jamin Katanwar",
  "Jangal Akbarpur",
  "Jangal Bindwalia",
  "Jangal Pachphera",
  "Janki Nagar",
  "Jarar",
  "Jarha",
  "Jogi Chhapra",
  "Judavan Chhapra",
  "Judawn Chhapra",
  "Jungal Jatha",
  "Jungal Piprasi",
  "Jungle Amwa",
  "Jungle Arazi Jatha",
  "Jungle Bakulha",
  "Jungle Banbirpur",
  "Jungle Bangali Patti",
  "Jungle Belwa",
  "Jungle Bishunpura",
  "Jungle Chauria",
  "Jungle Dharampur",
  "Jungle Gai Ghat",
  "Jungle Hanumanganj",
  "Jungle Jagdishpur",
  "Jungle Khirkia",
  "Jungle Kurmaul",
  "Jungle Nahar Chhapra",
  "Jungle Nonia Patti",
  "Jungle Pachrukhia",
  "Jungle Shahpur",
  "Jungle Singa Patti",
  "Jungle Sukhpura",
  "Jura Chhapra",
  "Jura Chhapra",
  "Jurwaniya",
  "Jwalapur",
  "Kalwari Patti",
  "Kalyan Chhapra",
  "Kanaura",
  "Kanthi Chhapra",
  "Kanthi Chhapra",
  "Kardah",
  "Karhia Hazari Patti",
  "Karmaini",
  "Karmha Mustaqil Karmha Aht.",
  "Karuawana Abadkari",
  "Kasia",
  "Katahimar Purwa",
  "Kathinahia",
  "Kathkuia",
  "Kati",
  "Katya",
  "Kauwasar",
  "Kesheo Chhapra",
  "Kewal Chhapra",
  "Khadda (NP)",
  "Khadda Buzurg",
  "Khadda Kalan",
  "Khadda Khurd",
  "Khadda Khurd",
  "Khaddi",
  "Khairatia Shitalpur",
  "Khairi",
  "Khairtia",
  "Khajuri",
  "Khajuria",
  "Khanu Chhapra",
  "Khanwar Baklolahi",
  "Khar Khajuria",
  "Khedu Chhapra",
  "Kheman Chhapra",
  "Khesia",
  "Khotahi",
  "Khudra",
  "Kinner Patti",
  "Kodauna",
  "Kohar Gaddi",
  "Koharwalia",
  "Kohra",
  "Kop Jungal",
  "Kotawa Khurd",
  "Kotwa Kalan",
  "Kuia",
  "Kukraha",
  "Kulman Chhapra",
  "Kundeli Patti",
  "Kurmaul Urf Sohanpur",
  "Kursaha",
  "Lakhua Khurd",
  "Lamkan",
  "Lamuha",
  "Langari",
  "Laukaria",
  "Laxmipur",
  "Lila Dhar Chhapra",
  "Lila Dhar Chhapra",
  "Luxmipur",
  "Luxmipur Mustaqil+Aht. Ramnaga",
  "Luxmipur Urf Kurmi Patti",
  "Madanpur Sukrauli",
  "Madar Bindwalia",
  "Madariha",
  "Madhopur",
  "Madhopur Gojahi",
  "Maghi",
  "Maghi Hardo",
  "Maghi Kothilwa",
  "Maghi Mathia",
  "Maghi Mustaqil+Aht.",
  "Maharani",
  "Mahdeva",
  "Maheshara",
  "Mahuawa",
  "Mahuawa",
  "Mahulania",
  "Maila",
  "Majra Kewal Chhapra",
  "Makhanha",
  "Malhia",
  "Malhia Mafi",
  "Mangalpur",
  "Mani Kaura",
  "Mania Chhapra",
  "Mansha Chhapra",
  "Mansha Chhapra 48",
  "Mansha Chhapra 52",
  "Marichahwa",
  "Mathia",
  "Mathia",
  "Mathia Alam",
  "Mathia Basant Pande",
  "Mathia Buzurg",
  "Mathia Dheer",
  "Mathia Jai Kishun",
  "Mathia Khurd",
  "Mathia Lal Bihari",
  "Mathia Prasiddh Tiwari",
  "Mathia Raghunath",
  "Mathia Ram Govind",
  "Mathiya Devi Sahay",
  "Mathiya Khurd",
  "Mathura Chhapra",
  "Matihania Buzurg",
  "Matihania Khurd",
  "Mhuawa",
  "Milki",
  "Mishrauli Abadkari",
  "Misir Patti",
  "Misrauli",
  "Misrauli",
  "Misrauli",
  "Mithha Mafi",
  "Mojahida Urf Baiju Patti",
  "Mojahida Urf Chirihwa",
  "Mojahidi Urf Aranhwa",
  "Moti Chhapra",
  "Moti Chhapra",
  "Motipur",
  "Mudmudwa",
  "Mundera",
  "Mundera",
  "Muzohida Khas",
  "Nadah",
  "Nagari",
  "Nand Lal Chhapra",
  "Nanda Chhapra",
  "Nar Chochawa",
  "Nar Kelia Mus.+ Aht.",
  "Narainpur",
  "Narainpur",
  "Narharia",
  "Narkahawa",
  "Narku Chhapra",
  "Naugaon Inrahi",
  "Naugawan",
  "Naurangia",
  "Nautan Hardo",
  "Nautar Jungal",
  "Nawal Chhapra",
  "Nebua Rai Ganj",
  "Newaz Chhapra",
  "Nirmal Patti",
  "Oharwalia",
  "Pach Phera",
  "Pachphera",
  "Padari",
  "Padari Piparpati",
  "Padrahi Urf Pakari",
  "Padrauna (NPP)",
  "Padri Mehdia",
  "Pagara Buzurg",
  "Paharpur",
  "Pakari Brijlal No.2",
  "Pakarihawa Mustaqil+ Aht.",
  "Pakaripar",
  "Pakariyar",
  "Pakha",
  "Pakhanha",
  "Pakri Brijlal No.1",
  "Pakri Buzurg",
  "Pakri Khurd",
  "Palat Chhapra",
  "Palia",
  "Pande Chhapra",
  "Panhiwa",
  "Parbat Chhapra",
  "Pargan Chhapra",
  "Parsadpur",
  "Parsauni",
  "Parsauni Kalan",
  "Parsia",
  "Parsu Rampur",
  "Patariya Abadkari",
  "Patera Buzurg",
  "Patera Khurd",
  "Paterha",
  "Patilar",
  "Patkhauli",
  "Patkhauli",
  "Phatak Dauna Hira Chhapra",
  "Phatak Dauna Khas",
  "Pipar Sujan",
  "Piparia",
  "Piparpati",
  "Pipra Buzurg",
  "Pipra Buzurg",
  "Pipra Jatanpur",
  "Pipra Jawahir",
  "Pipra Khurd",
  "Pipra Khurd",
  "Pipra Majra Dharampur",
  "Pipra Sobhmal",
  "Piprasi",
  "Piprasi Mus.+ Aht.",
  "Piprawar Siwan",
  "Pipria Narhar",
  "Pradhan Patti",
  "Purnaha Buzurg",
  "Purnaha Misra",
  "Rahasu",
  "Raiganj",
  "Raipur Banjari",
  "Raipur Bhaisahi",
  "Raipur Khopa",
  "Raipur Phulwari",
  "Rajman Chhapra",
  "Ramji Patti",
  "Ramnagar",
  "Ramnagar Misrauli",
  "Ramnagar Sargatia",
  "Rampur",
  "Rampur Bangar",
  "Rampur Bhat",
  "Rampur Gonha",
  "Rampur Jungal",
  "Rampur Khas",
  "Rampur Khurd",
  "Ranjita Jungal",
  "Rasulpur",
  "Ratanwa",
  "Ruari",
  "Rudrapur",
  "Sadi Buzurg",
  "Sadi Chhapra",
  "Sadi Khurd",
  "Sagar",
  "Sagar Gosai",
  "Sahajwalia",
  "Sahodar Patti",
  "Sahuadih",
  "Sakhya Abadkari",
  "Salikpur Mus.+ Aht.",
  "Sarang Chhapra",
  "Sarang Chhapra",
  "Sargaria Urf Ramnagar",
  "Sargatia",
  "Sarpathi Buzurg",
  "Sarpathi Khurd",
  "Sarya",
  "Saurha Buzurg",
  "Saurha Khurd",
  "Sehui Khas",
  "Sekhui",
  "Sekhui Bazar",
  "Sekhui Kaf",
  "Sekhui Mishra",
  "Semara Hardo",
  "Semra",
  "Semra",
  "Semria Kalan",
  "Semria Khurd",
  "Sewak Chhapra",
  "Sewak Chhapra",
  "Shahpur",
  "Shambhu Chhapra",
  "Shampur",
  "Shesha Chhapra",
  "Shiv Datt Chhapra",
  "Shivpur",
  "Shobha Chhapra 51",
  "Shobha Chhapra 67",
  "Shripati Chhapra",
  "Shukul Patti",
  "Sidhua",
  "Sidhua Bagar Bhath",
  "Siganjori",
  "Sigha",
  "Sikta",
  "Sirsia",
  "Sirsia",
  "Sirsia Bir Bhan",
  "Sirsia Buzurg",
  "Sirsia Kalan",
  "Sirsia Khurd",
  "Sirsia Sagar",
  "Sisai Dadhich",
  "Sishan",
  "Siswa Goiti",
  "Siswa Gopal",
  "Siswa Mani Raj",
  "Siswa Mathia",
  "Siswa Prithvi Shahi",
  "Siswa Ramsahai",
  "Siswa Urf Siswania",
  "Sita Chhapra",
  "Sohanaria",
  "Sohrauna",
  "Sohrauna",
  "Sohrauna",
  "Sonbarsa",
  "Sonwal",
  "Sugahi",
  "Sukh Chhapra",
  "Sukhari Chhapra",
  "Surajpur",
  "Suswalia",
  "Tadawa",
  "Teen Vardaha",
  "Tegraha Chak No.3",
  "Tegraha Chak No.4",
  "Tegraha Chak No.5",
  "Tegraha Chak No.6",
  "Tejwalia",
  "Terhi",
  "Thagda",
  "Tinparsa",
  "Tirlokpur Buzurg",
  "Tirlokpur Khurd",
  "Turkaha",
  "Turkhi",
  "Udho Chhapra",
  "Vijaipur",
  "Vijaypur",
  "Vindhyachalpur",
  "Vishunpur Vijaipur",
  "Vishunpura Buzurg"
]
console.log(arr);
