let arr = [  "Ahiraule",
  "Ahirauli Dan",
  "Ahirauli Hanuman Singh",
  "Ahirauli Mishra",
  "Ahirauli Raja",
  "Ahirauli Talwant Shahi",
  "Ahladpur",
  "Amahi",
  "Amarwa Buzurg",
  "Amarwa Khurd",
  "Amwa",
  "Amwa Khas",
  "Amwadiger",
  "Araji Gadai Patti",
  "Araji Sumahi",
  "Arazi Bhagwanpur",
  "Arazi Bundel Giri",
  "Arazitalvant Ray",
  "Asokawa Buzurg",
  "Asokawa Khurd",
  "Audan Tola",
  "Babhanauli",
  "Babhnauli",
  "Babhnauli",
  "Badahara Brit",
  "Badahara Buzurg",
  "Badahara Dubey",
  "Badahara Khurd",
  "Bagahi",
  "Baghachaur",
  "Bahadurpur",
  "Bahira Bari",
  "Baiju Patti",
  "Baikunthpur",
  "Baluatakia",
  "Baluwa Samsher Shahi",
  "Banaraha Pachhim Patti",
  "Banaraha Purab Patti",
  "Banbeera",
  "Bangara Ram Bux Rai",
  "Banka Khas",
  "Bans Gaon",
  "Banwaria",
  "Barai Patti",
  "Barampur",
  "Barawa Mishrauli",
  "Bardha Pandey",
  "Baria",
  "Barwa",
  "Barwa Rajapakar",
  "Basantpur Hari Charan Rai",
  "Basantpur Raja",
  "Basantpur Ramlagan Rai",
  "Basdila Buzurg",
  "Basdila Gunagar",
  "Basdila Khurd",
  "Basdilla Mahant",
  "Batarauli Dhur Khandwa",
  "Batrauli",
  "Bedupar Ahatmali",
  "Bedupar Mu.",
  "Beni Bhar",
  "Bhagawanpur",
  "Bhaisaha",
  "Bhaluhi",
  "Bharapatia",
  "Bhatawalia",
  "Bhavpur",
  "Bhelahi",
  "Bhelya",
  "Bhelya Uttar Diha Ramsahai",
  "Bhual Patti",
  "Bhuli Agarwa",
  "Bhuswalia",
  "Bichpatwa",
  "Bihar Buzurg",
  "Bihar Khurd",
  "Bijaipur Dakhin Patti",
  "Bijaipur Uttar Patti",
  "Birwat Komwalia",
  "Bishunpur Baria Patti",
  "Bishunpura",
  "Bishunpura",
  "Chaf",
  "Chain Patti",
  "Chakhani Dukhi Mishra",
  "Chakhani Khas",
  "Chandravta",
  "Chaubia Patkhauli",
  "Chaupthia",
  "Chhapara Ahirauli",
  "Chhapra Dalrai",
  "Chir Kutaha",
  "Daniari",
  "Dasahwa",
  "Deo Pokhar",
  "Deoria Bishundayal",
  "Deoria Brat",
  "Deoria Khurd",
  "Dharampur Khurd",
  "Dharmathia",
  "Dharmauli",
  "Dhokaraha",
  "Dhum Patti",
  "Dhuria Emiliya",
  "Dhuria Kot",
  "Dibani Banjarwa",
  "Doawanha",
  "Doihara",
  "Domantarya",
  "Domath",
  "Dubauli",
  "Dubha",
  "Dudhi",
  "Dumahi",
  "Dumar Bhar",
  "Dumaria",
  "Fagu Chhapra",
  "Gadai Patti",
  "Gadari",
  "Gagalwa",
  "Gagalwa",
  "Ganesh Patti",
  "Gangalwa",
  "Gangi Tikar",
  "Ganguawa",
  "Garhia Mohan",
  "Garhia Pathak",
  "Garhiachinta Mani",
  "Gauri Ebrahim",
  "Gauri Jagdish",
  "Gauri Narottam",
  "Gauri Shri Ram",
  "Gauri Sukul",
  "Ghaghwa Jagdish Ahatmali",
  "Ghaghwa Jagdish Mu.",
  "Ghazipur",
  "Godaria",
  "Gopalpur",
  "Goraita Shri Ram",
  "Gosai Patti",
  "Govind Patti",
  "Gurwalia",
  "Hafua Balram",
  "Hafua Chatur Bhuj",
  "Hafua Jeewan",
  "Hanumanganj",
  "Hardiya",
  "Haribansh Patti",
  "Hariharpur",
  "Harkhauli",
  "Harpur",
  "Hata",
  "Hata",
  "Hauda",
  "Jabhi Narendra",
  "Jagdishpur",
  "Jalal Chhapra",
  "Jalal Chhapra Ahatmali",
  "Jamsara",
  "Jamsaria",
  "Jangle Bishunpura",
  "Jangle Lala Chhapra",
  "Jauh Malhi Ahatmali",
  "Jawahihar Ballabh",
  "Jawar",
  "Jawhi Dyal",
  "Jawhider Hakeekat Parsauni",
  "Jawhimalhi Mustkil",
  "Jawhimath Chulahi",
  "Jharwa",
  "Jogia Bichli Patti",
  "Jogia Hichharai",
  "Jogia Janubi Patti",
  "Jogia Shomli Patti",
  "Jungle Ghorath",
  "Jungle Luathaha",
  "Jungle Naugawan",
  "Jungle Siswa",
  "Karan Patti",
  "Karimchak",
  "Karmaha",
  "Karmoni",
  "Kataura",
  "Kataura",
  "Kathwalia Urf Habibpur",
  "Khairatia",
  "Khalwa Patti",
  "Khiriya",
  "Khudra-Ahirauli",
  "Khudura",
  "Kirat Patti",
  "Kishun Das Patti",
  "Kishun Deo Patti",
  "Kitamantal",
  "Koindha",
  "Koindi Bariyarpur",
  "Koindi Buzurg",
  "Koindi Gosai Patti",
  "Koindi Khurd",
  "Kokil Patti",
  "Korya",
  "Korya Bhelahi",
  "Kotwa",
  "Kotwa",
  "Kotwa Gulabrai",
  "Koyar Patti",
  "Kuber Patti",
  "Lachhia Deoria",
  "Latwa Jit",
  "Latwa Muralidhar",
  "Lav Kush Purab Patti",
  "Lawania",
  "Laxmipur Buzurg",
  "Laxmipur Raja",
  "Loh Langari",
  "Lohar Patti",
  "Machhariha Basant Bharati",
  "Machhariha Daljit Kunwar",
  "Madhavpur Khurd",
  "Madhopur Buzurg",
  "Maguri Patti",
  "Maheshpur",
  "Mahuawa",
  "Mahuawa Buzurg",
  "Mahuawa Khurd",
  "Majhaua",
  "Makhua",
  "Malho",
  "Manjharia",
  "Marawa",
  "Mathauli",
  "Mathauli",
  "Mathia",
  "Mathia",
  "Mathia Bhakariya",
  "Mathia Bujurg",
  "Mathia Kartar Giri",
  "Mathia Khurd",
  "Mathia Shri Ram",
  "Mathia Shri Ram Aht",
  "Mathiamafi Urf Dukhi Ganeshpur",
  "Matloob Chapar",
  "Mehadia Khurd",
  "Mehadiya Bugurg",
  "Mirbihar",
  "Mishrauli",
  "Mishrauli",
  "Misrauli",
  "Mogalpura",
  "Mohan Basdila",
  "Morwan",
  "Mukund Chhaper",
  "Mukundpur",
  "Munni Patti",
  "Nainu Pahru",
  "Nakataha Basdila",
  "Narahwa",
  "Narainpur Araji",
  "Narainpur Raja",
  "Narayanpur",
  "Narayanpur",
  "Narhawa Dih",
  "Narhawa Urf Maila",
  "Narhwa Achraj Dubey",
  "Naugawan",
  "Nirahuganj",
  "Noniya Patti",
  "Padaraha",
  "Padari",
  "Padari Bishun Dayal",
  "Padari Raja",
  "Padari Tilakrai",
  "Padraun Madurahi",
  "Pagara Parari",
  "Pagara Prasad Giri",
  "Pakari",
  "Pakari Gosai Patti",
  "Pakhihawa Urf Karanjaha",
  "Pakriar Pachim Patti",
  "Pakriyarpurab Patti",
  "Pandey Patti",
  "Pandey Patti",
  "Pandeypur",
  "Pandeypur",
  "Pandeypur Urf Basantpur",
  "Pansarwa",
  "Parasaubi Khurd",
  "Parasauni Buzurg",
  "Parsa Urf Sirsia Ahatmali",
  "Parsaoni Khurd",
  "Parsaun",
  "Parsauni",
  "Parsauni Doyam",
  "Parsauni Janubi",
  "Parsauni Sumali",
  "Parsaurf Sirsia Mu.",
  "Parsnuni Auwal",
  "Parvat Chhapar",
  "Patharwa",
  "Patherwa",
  "Patkhauli",
  "Pipara Baghel",
  "Pipara Mustquil Agarwa",
  "Pipra Kanak",
  "Pipra Misra",
  "Pipraghat Ahatmali",
  "Pipraghat Mustkil",
  "Pirathipur",
  "Pirojaha",
  "Puraina Kateya",
  "Raja Pakar",
  "Rajawatia",
  "Rakaba Dulama Patti",
  "Rakbajunglli Patti",
  "Rakbaraja",
  "Ramchandrapur",
  "Ramnagar",
  "Rampur Bangr",
  "Rampur Barahan",
  "Rampur Jamunia",
  "Rampur Patti",
  "Rampur Raja",
  "Razpur Bagaha",
  "Razpur Khas",
  "Salemgarh",
  "Sangrampur",
  "Sapaha",
  "Sapahi Buzurg",
  "Sapahi Khas",
  "Sapahi Khurd",
  "Saphi",
  "Saragatia Karan Patti",
  "Sarai Buzurg",
  "Sarai Khurd",
  "Sariswa",
  "Semara Hardo Patti",
  "Senduria Buzurg",
  "Senduria Khurd",
  "Sewarhi (NP)",
  "Sewrahi",
  "Shahdauli",
  "Shahpur Mafi",
  "Shahpur Uchaki Patti",
  "Shankarpur",
  "Shapur Khalwa Patti",
  "Shyam Patti",
  "Sikatia",
  "Siswa Awwal",
  "Siswa Buzurg",
  "Siswa Digar",
  "Sondiya Buzurg",
  "Sorahwa",
  "Sri Ram Patti",
  "Sukulahe",
  "Sultanpur",
  "Sumahi Bujurg Urf Mahediya",
  "Sumahi Mohan Singh",
  "Sumahi Santpatti",
  "Sumuhi Rani",
  "Sumuhi Sangram",
  "Tamakuhi Raj",
  "Tandwa",
  "Tar Bishunpur",
  "Tarya Baikunth",
  "Tarya Jamin",
  "Tarya Lachhiram",
  "Tarya Sujan",
  "Tarya Sunder",
  "Taryaharkesh",
  "Tejwalia",
  "Tetaria",
  "Thari Bhar",
  "Tikampar",
  "Tikulia",
  "Tilak Patti",
  "Tinfaria",
  "Tirama Sahun",
  "Tiwari Patti",
  "Tola Shiwatamrai",
  "Tulsi Patti",
  "Turkpatti",
  "Turkwalia Sahabganj",
  "Uttar Diha Sadashive Sahai",
  "Uttardiha Shabin Shahi"
]
